version: '3.3'

services:
  firebase-hosting:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    environment:
      - FIREBASE_TOKEN=${FIREBASE_TOKEN}
    command: ["firebase", "emulators:start", "--only", "hosting", "--project", "bytefusion-fcc03"]